// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmcbtivchziawaamntfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptY2J0aXZjaHppYXdhYW1udGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDk1NjksImV4cCI6MjA1OTI4NTU2OX0.GoPJmIIwrBBV2m2zoG54FJUaYH_3nn32XGBWlNr6cRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);